# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Create download directory
ENV DOWNLOAD_PATH=/data
RUN mkdir -p ${DOWNLOAD_PATH}

# Install dependencies
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir \
    feedparser>=6.0.11 \
    httpx>=0.28.1 \
    "mcp[cli]>=1.6.0" \
    pymupdf>=1.25.5

# Copy source code
COPY src ./src

# Expose no ports (stdio)

# Start the MCP server
ENTRYPOINT ["python", "src/arxiv_server/server.py"]
